num1 = float(input("Første tall: "))
num2 = float(input("Andre tall: "))

print("Addert:", num1 + num2)
print("Subtrahert:", num1 - num2)
print("Multiplisert:", num1 * num2)
print("Dividert:", num1 / num2)
print("Modulo:", num1 % num2)
print("Potens:", num1 ** num2)
print("Heltallsdivisjon:", num1 // num2)